// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dust3rServiceProto.proto

package org.panorama.walkthrough.grpc;

public interface ComputeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dust3r.ComputeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
