// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dust3rServiceProto.proto

package org.panorama.walkthrough.grpc;

public interface ComputeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dust3r.ComputeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string result = 1;</code>
   * @return The result.
   */
  String getResult();
  /**
   * <code>string result = 1;</code>
   * @return The bytes for result.
   */
  com.google.protobuf.ByteString
      getResultBytes();
}
