// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dust3rServiceProto.proto

package org.panorama.walkthrough.grpc;

public final class Dust3RServiceProto {
  private Dust3RServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dust3r_ComputeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dust3r_ComputeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dust3r_ComputeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dust3r_ComputeResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\030dust3rServiceProto.proto\022\006dust3r\"!\n\016Co" +
      "mputeRequest\022\017\n\007message\030\001 \001(\t\"!\n\017Compute" +
      "Response\022\016\n\006result\030\001 \001(\t2K\n\rDust3rServic" +
      "e\022:\n\007Compute\022\026.dust3r.ComputeRequest\032\027.d" +
      "ust3r.ComputeResponseB!\n\035org.panorama.wa" +
      "lkthrough.grpcP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_dust3r_ComputeRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dust3r_ComputeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dust3r_ComputeRequest_descriptor,
        new String[] { "Message", });
    internal_static_dust3r_ComputeResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_dust3r_ComputeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dust3r_ComputeResponse_descriptor,
        new String[] { "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
